# Generated by Django 4.1 on 2022-08-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admingrafic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='График')),
                ('decimalx', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='ось x')),
                ('decimaly', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='ось y')),
            ],
        ),
    ]
